version: "3.1"

services:
  nextcloud:
    image: nextcloud:fpm
    container_name: nextcloud
    restart: always
    mem_limit: 2048m
    mem_reservation: 512m
    networks:
      - nextcloud_net
      - web_proxy
    depends_on:
      - nextcloud_db
      - nextcloud_cache
    links:
      - nextcloud_db
    entrypoint: sh -c '/wait-for-it.sh nextcloud_db:5432 --timeout=5 -- /entrypoint.sh php-fpm'
    secrets:
      - nextcloud_admin_user
      - nextcloud_admin_password
      - nextcloud_postgres_db
      - nextcloud_postgres_user
      - nextcloud_postgres_password
      - nextcloud_redis_password
    environment:
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/nextcloud_admin_user
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.jakehamzawi.net
      POSTGRES_HOST: nextcloud_db
      POSTGRES_USER_FILE: /run/secrets/nextcloud_postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/nextcloud_postgres_password
      POSTGRES_DB_FILE: /run/secrets/nextcloud_postgres_db
      REDIS_HOST: nextcloud_cache
      REDIS_HOST_PASSWORD: passtest
    volumes:
      - ${ROOT}/wait-for-it.sh:/wait-for-it.sh
      - ${CACHE}/var/www/html:/var/www/html
      - ${DATA}/data:/var/www/html/data
      - ${CACHE}/var/www/html/config:/var/www/html/config
        # Custom settings for php fpm to make nextcloud work. The default settings resulted in the error:
        # WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
      - ${ROOT}/www-custom.ini:/usr/local/etc/php-fpm.d/zz-custom.conf

  nextcloud_db:
    container_name: nextcloud_db
    image: postgres:alpine
    restart: always
    hostname: nextcloud_db
    networks:
      - nextcloud_net
    secrets:
      - nextcloud_postgres_user
      - nextcloud_postgres_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/nextcloud_postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/nextcloud_postgres_password
    volumes:
      - ${CACHE}/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  nextcloud_cache:
    container_name: nextcloud_cache
    image: redis:alpine
    restart: always
    mem_limit: 2048m
    mem_reservation: 512m
    networks:
      - nextcloud_net
    secrets:
      - nextcloud_redis_password
    volumes:
      - ${ROOT}/redis-entrypoint.sh:/entrypoint.sh
    command: redis-server --requirepass passtest

networks:
  web_proxy:
    external: true
  nextcloud_net:
    driver: bridge

secrets:
  nextcloud_admin_user:
    file: ${ROOT}/secrets/nextcloud_admin_user
  nextcloud_admin_password:
    file: ${ROOT}/secrets/nextcloud_admin_password
  nextcloud_postgres_db:
    file: ${ROOT}/secrets/nextcloud_postgres_db
  nextcloud_postgres_user:
    file: ${ROOT}/secrets/nextcloud_postgres_user
  nextcloud_postgres_password:
    file: ${ROOT}/secrets/nextcloud_postgres_password
  nextcloud_redis_password:
    file: ${ROOT}/secrets/nextcloud_redis_password
