version: "3.1"
services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: always
    networks:
      - web_proxy
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ${ROOT}/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${CACHE}/caddy/caddy-config:/config
      - ${CACHE}/caddy/caddy-data:/data
      - ${CACHE}/nextcloud/var/www/html:/nextcloud/var/www/html
      - ${NEXTCLOUD_DATA}:/nextcloud/var/www/html/data
    environment:
      - LOG_FILE=${LOG_FILE}
      - EMAIL=${EMAIL}

networks:
  web_proxy:
    external: true 

