version: "3.0"
services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CACHE}/config:/config
    networks:
      - web_proxy
      - media_dl_net
    restart: unless-stopped

networks:
  web_proxy:
    external: true
  media_dl_net:
    external: true
