version: "3.1"
services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: always
    env_file:
      - ./secrets/secrets.env
    networks:
      - media_dl_proxy
      - ombi_proxy
      - radicale_proxy
      - vaultwarden_proxy
      - nextcloud_proxy
      - immich_proxy
      - adguardhome_proxy
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${CACHE}/caddy/caddy-config:/config
      - ${CACHE}/caddy/caddy-data:/data
      - ${CACHE}/nextcloud/var/www/html:/nextcloud/var/www/html
      - ${NEXTCLOUD_DATA}:/nextcloud/var/www/html/data
    environment:
      - LOG_FILE=${LOG_FILE}
      - TZ=${TZ}

networks:
  media_dl_proxy:
    external: true
  ombi_proxy:
    external: true
  radicale_proxy:
    external: true
  vaultwarden_proxy:
    external: true
  nextcloud_proxy:
    external: true
  immich_proxy:
    external: true
  adguardhome_proxy:
    external: true

