version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    secrets:
      - vw_admin_token
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN_FILE=/run/secrets/vw_admin_token
    volumes:
      - ${CACHE}/vw-data:/data
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true
secrets:
  vw_admin_token:
    file: ${ROOT}/secrets/vw_admin_token
