version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${CACHE}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    command: '-f "" -r 172.19.0.0/16' # enable firewall and route local network traffic
    networks:
      - media_dl_net
      - media_dl_proxy

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${MEDIA_ROOT}/downloads:/downloads # downloads folder
      - ${CACHE}/config/deluge:/config # config files

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr 
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CACHE}/config/prowlarr:/config
    networks:
      - media_dl_net
      - media_dl_proxy

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped 
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    networks:
      - media_dl_net

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CACHE}/config/sonarr:/config # config files
      - ${PLEX_ROOT}/tv:/tv # tv shows folder
      - ${MEDIA_ROOT}/downloads:/downloads # download folder
    networks:
      - media_dl_net
      - media_dl_proxy

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CACHE}/config/radarr:/config # config files
      - ${PLEX_ROOT}/movies:/movies # movies folder
      - ${MEDIA_ROOT}/downloads:/downloads # download folder
    networks:
      - media_dl_net
      - media_dl_proxy

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${CACHE}/config/bazarr:/config # config files
      - ${PLEX_ROOT}/movies:/movies # movies folder
      - ${PLEX_ROOT}/tv:/tv # tv shows folder
    networks:
      - media_dl_net
      - media_dl_proxy

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CACHE}/config/lidarr:/config
      - ${PLEX_ROOT}/music:/music
      - ${MEDIA_ROOT}/downloads:/downloads
    networks:
      - media_dl_net
      - media_dl_proxy

networks:
  media_dl_net:
    external: true
  media_dl_proxy:
    external: true
