version: "3.1"

services:
  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    restart: always
    mem_limit: 2048m
    mem_reservation: 512m
    networks:
      - nextcloud_net
    ports:
      - 9000:80
    depends_on:
      - nextcloud_db
      - nextcloud_cache
    links:
      - nextcloud_db
    entrypoint: sh -c '/wait-for-it.sh nextcloud_db:5432 --timeout=5 -- /entrypoint.sh apache2-foreground'
    secrets:
      - nextcloud_admin_user
      - nextcloud_admin_password
      - nextcloud_postgres_db
      - nextcloud_postgres_user
      - nextcloud_postgres_password
#      - nextcloud_redis_password
    environment:
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/nextcloud_admin_user
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password
      NEXTCLOUD_TRUSTED_DOMAINS: "cloudl.jakehamzawi.net cloud.jakehamzawi.net"
      POSTGRES_HOST: nextcloud_db
      POSTGRES_USER_FILE: /run/secrets/nextcloud_postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/nextcloud_postgres_password
      POSTGRES_DB_FILE: /run/secrets/nextcloud_postgres_db
      REDIS_HOST: nextcloud_cache
      REDIS_HOST_PASSWORD:
      # Redis password authentication is apparently broken (unable to run
      # occ commands when password is enabled). Password is blank
      #REDIS_HOST_PASSWORD_FILE: /run/secrets/nextcloud_redis_password
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ${CACHE}/var/www/html:/var/www/html
      - ${DATA}/data:/var/www/html/data
      - ${CACHE}/var/www/html/config:/var/www/html/config
        # Custom settings for php fpm to make nextcloud work. The default settings resulted in the error:
        # WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
      - ./www-custom.ini:/usr/local/etc/php-fpm.d/zz-custom.conf

  nextcloud_db:
    container_name: nextcloud_db
    image: postgres:alpine
    restart: always
    hostname: nextcloud_db
    networks:
      - nextcloud_net
    secrets:
      - nextcloud_postgres_user
      - nextcloud_postgres_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/nextcloud_postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/nextcloud_postgres_password
    volumes:
      - ${CACHE}/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  nextcloud_cache:
    container_name: nextcloud_cache
    image: redis:alpine
    restart: always
    mem_limit: 2048m
    mem_reservation: 512m
    command: redis-server /usr/local/etc/redis/redis.conf 
    networks:
      - nextcloud_net
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
#    secrets:
#      - nextcloud_redis.acl


networks:
  nextcloud_net:
    driver: bridge

secrets:
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password
  nextcloud_postgres_db:
    file: ./secrets/nextcloud_postgres_db
  nextcloud_postgres_user:
    file: ./secrets/nextcloud_postgres_user
  nextcloud_postgres_password:
    file: ./secrets/nextcloud_postgres_password
#  nextcloud_redis_password:
#    file: ./secrets/nextcloud_redis_password
#  nextcloud_redis.acl:
#    file: ./secrets/nextcloud_redis.acl
