version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file:
      - ./secrets/secrets.env
    secrets:
      - vw_admin_token
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SENDS_ALLOWED=true
      - SIGNUPS_VERIFY=false
      - INVITATIONS_ALLOWED=true
      - INVITATION_ORG_NAME="Hamzawi Vaultwarden"
#      - ADMIN_TOKEN_FILE=/run/secrets/vw_admin_token
    volumes:
      - ${CACHE}/vw-data:/data
    networks:
      - vaultwarden_proxy

networks:
  vaultwarden_proxy:
    external: true
secrets:
  vw_admin_token:
    file: ./secrets/vw_admin_token
