version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    networks:
      - web-proxy
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    ports:
      - "3306:3305"
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db:
networks:
   web-proxy:
     external: true
