version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${MEDIA_ROOT}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge to be available from outside
    command: '-f "" -r 192.168.86.0/24' # enable firewall and route local network traffic
    networks:
      - media_dl_net

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${MEDIA_ROOT}/downloads:/downloads # downloads folder
      - ${MEDIA_ROOT}/config/deluge:/config # config files

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr 
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_ROOT}/config/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - media_dl_net

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped 
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    networks:
      - media_dl_net

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT}/config/sonarr:/config # config files
      - ${PLEX_ROOT}/tv:/tv # tv shows folder
      - ${MEDIA_ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989
    networks:
      - media_dl_net

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT}/config/radarr:/config # config files
      - ${PLEX_ROOT}/movies:/movies # movies folder
      - ${MEDIA_ROOT}/downloads:/downloads # download folder
    ports:
      - 7878:7878
    networks:
      - media_dl_net

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${MEDIA_ROOT}/config/bazarr:/config # config files
      - ${PLEX_ROOT}/movies:/movies # movies folder
      - ${PLEX_ROOT}/tv:/tv # tv shows folder
    ports:
      - 6767:6767
    networks:
      - media_dl_net

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_ROOT}/config/lidarr:/config
      - ${PLEX_ROOT}/music:/music
      - ${MEDIA_ROOT}/downloads:/downloads
    ports:
      - 8686:8686
    networks:
      - media_dl_net

networks:
  media_dl_net:
    external: true
