version: "3.0"
services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CACHE}/config:/config
    networks:
      - media_dl_net
      - ombi_proxy

networks:
  media_dl_net:
    external: true
  ombi_proxy:
    external: true

