version: "2.1"
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    env_file:
      - ./secrets/secrets.env
    networks:
      - media_dl_net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - TZ=${TZ}
#     - ADVERTISE_IP    # Set in secrets.env
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${CACHE}/config:/config
      - ${DATA}/tv:/tv
      - ${DATA}/movies:/movies
      - ${DATA}/music:/music
    ports:
      - 32400:32400
#      - 3005:3005
#      - 5353:5354/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped

networks:
  media_dl_net:
    external: true
