version: '3.5'

services:
  db:
    image: mariadb:10.1
    container_name: filerun_db
    restart: unless-stopped
    networks:
      - filerun_net
    secrets:
      - filerun_db_root_password
      - filerun_db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/filerun_db_root_password
      MYSQL_USER: filerun
      MYSQL_PASSWORD_FILE: /run/secrets/filerun_db_password
      MYSQL_DATABASE: filerun
    volumes:
      - ${CACHE}/mysql:/var/lib/mysql

  web:
    image: filerun/filerun
    container_name: filerun
    restart: unless-stopped
    entrypoint: /filerun/docker-entrypoint.sh
    networks:
      - filerun_net
      - web_proxy
    secrets:
      - filerun_db_password
    environment:
      TZ: ${TZ}
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS_FILE: /run/secrets/filerun_db_password
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - ${CACHE}/html:/var/www/html
      - ${DATA}/files:/user-files
      - ${ROOT}/docker-entrypoint.sh:/filerun/docker-entrypoint.sh

networks:
  filerun_net:
    name: filerun_net
    driver: bridge
  web_proxy:
    external: true

secrets:
  filerun_db_root_password:
    file: ${ROOT}/secrets/filerun_db_root_password
  filerun_db_password:
    file: ${ROOT}/secrets/filerun_db_password
